name: Update Submodules and Publish

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-submodules]
  push:
    branches:
      - main

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update Git submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive 'git fetch origin gh-pages'
          git submodule update --remote --merge -v 
          git add .
          git commit -m "Update submodules to latest commit" || echo "No changes to commit"

      - name: Push changes
        run: |
          - git push origin HEAD:main
          - env:
          - GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}